feat/분실물 등록 스크린
L-OCAT/Client-old pull request #8
Opened 2024-08-29 09:15 UTC by crucial-sub

## 📝작업 내용
- 분실물 등록 스크린 구현
  - 이미지 업로드 기능 (ImagePicker 컴포넌트)
    - 최대 10장 업로드 가능
    - 대표 이미지 선택 기능
    - 추후 재사용 용이하도록 useImagePicker 커스텀 훅 작성
  - 카테고리 선택 기능
  - 색상 선택 기능
  - 물건명, 상세설명 입력 기능
  - 보상금 지급 의사 체크박스 기능
  - '다음' 버튼 (필수 입력 항목 모두 입력 시 활성화)
- 키보드 입력 시 UI 조정 기능
  - KeyboardAwareScrollView를 사용하여 키보드에 의해 하단의 multiLine textInput이 가려지지 않도록 구현
  - react-native-reanimated를 사용하여 부드러운 애니메이션 효과 적용(키보드가 올라올때 버튼이 키보드 위로 같이 올라감)
    - 키보드 show/hide 시 '다음' 버튼 위치 자연스럽게 이동
  - iOS와 Android 플랫폼 차이를 고려한 구현(iOS에서는 키보드가 화면 공간을 차지하지만, 안드로이드에서는 키보드가 올라올 때 자동으로 화면 크기를 조정.)
- Recoil을 사용한 상태 관리
  - 분실물 관련 정보(이미지, 물건명, 설명 등)를 Recoil atom으로 관리
  - 필수 입력 항목 완료 여부, 특수 카테고리/색상 선택 여부 등을 selector로 관리
- 뒤로가기 발생 시 state 리셋 (useResetOnBackNavigation 커스텀 훅 작성)
     - 헤더 버튼, 안드로이드 디바이스 버튼, iOS 스와이프 제스쳐 모두 대응

## 💬리뷰 요구사항
1. KeyboardAwareScrollView와 react-native-reanimated를 사용해서 키보드 대응 로직을 짰는데 iOS와 안드로이드가 키보드 처리하는 방식이 달라서 로직이 상당히 복잡하네요ㅠ 일단 수정님 환경에서도 정상 작동하는지 확인 부탁드려요..
2. 최상위 container에 screenLayout 스타일을 주던 방식에서 그냥 보다 간편하게 최상위 View를 모두 SafeAreaView로 바꾸고 스타일에 flex:1 을 주는 방식으로 대체했어요! 추후 스크린 작성하실때도 최상위 View는 SafeAreaView로 작성 부탁드려요 :)
3. 여러 스크린에서 사용할 state를 관리하기 위한 전역상태관리 도구로 첫 회의 때 말씀드렸던 recoil을 도입해봤습니다!
recoil 사용방식 중 atom은 매우 간단한 편이지만 selector는 처음 사용하시면 조금 이해 어려운 부분도 있어서 제가 공부할 때 도움됐던 링크 남겨드려요!
https://velog.io/@2ast (좌측 태그 목록에서 recoil 태그 선택 혹은 검색칸에 recoil 검색)
https://tech.osci.kr/recoil-state-management-of-react/
https://tech.osci.kr/recoil-selector/

4. 새로 추가한 파일과 폴더들이 많아서 전반적인 코드 구조와 네이밍이 적절한지 피드백 주시면 감사하겠습니다

2024-08-30 08:01 UTC, comme-modee requested changes

2024-08-30 08:01 UTC, comme-modee commented on src/screens/LostItem/LostItemRegistrationScreen.tsx
>          <View style={styles.contentsWrapper}>
1. 한 화면에 요소들이 들어오게 작업하신 것 같은데 제 화면에서는 잘리는 부분이 생기더라고요. 전체적으로 View로 되어있는 걸 ScrollView로 바꿔야하나 싶은 생각이 들어요. 
![image](https://github.com/user-attachments/assets/d3eb6f2f-eb6c-4534-b604-adcbf177feb5)
![image](https://github.com/user-attachments/assets/0c8b2cbb-6d86-45a9-8907-a02017f06a82)
![image](https://github.com/user-attachments/assets/e5f301b0-877e-4af7-8aab-f67e68d2e859)


2. 물건명, 카테고리, 색상, 상세설명 글자랑 input 열이 안맞아서 일자로 맞게끔 조정해야 할 것 같아요!
![image](https://github.com/user-attachments/assets/582e2215-28bb-427b-9f9b-7ef3ffbfa987)

2024-08-30 08:01 UTC, comme-modee commented on src/components/lostItem/ImagePicker.tsx
이미 사진을 10장 올린 상태에서 또 사진첨부 버튼을 누를 경우 아래 참고사진과 같은 토스트메시지를 띄우면 어떨까 싶어요.

![image](https://github.com/user-attachments/assets/d0b8b7e2-5928-4c5c-9534-28de1e597c3d)

2024-08-30 08:01 UTC, comme-modee commented on src/components/lostItem/CategorySelector.tsx
> +  const getCategoryText = () => {
코드 상에서 category가 반복되는 것 같아서 아래와 같은 형식으로 작성하면 어떨까 해서 제안드립니다!

const getCategoryText = () => {
    const { main, sub } = category;

    if (!main) return null;
    return sub ? `${main}>${sub}` : main;
  };
  
그리고 서브카테고리가 선택되어야만 선택완료 버튼이 활성화되는 것 같은데 코드상에서는 서브카테고리가 선택되지 않을 경우 메인카테고리만을 리턴받을 수 있게 되는 것 같아 이 점 확인 부탁드릴게요! 아래와 같이 수정되어야 하는 것 아닌가 싶어요. (참고로 수정하지 않으셔도 작동은 문제없이 됩니다! 다만 화면 ui랑 코드내용이랑 일치시키면 더 좋지 않을까 해서요 ㅎㅎ)

const getCategoryText = () => {
  const { main, sub } = category;

  if (main && sub) {
    return `${main}>${sub}`;
  }
  return null;
};

2024-08-30 08:01 UTC, comme-modee commented on src/components/lostItem/ColorSelector.tsx
> +  const getColorText = () => {
코드를 삼항 연산자를 이용해서 한줄로 정리하면 어떨까 싶어 제안드립니다!

const getColorText = () => colors.length ? colors.join(', ') : null;

2024-08-30 08:32 UTC, crucial-sub commented on src/screens/LostItem/LostItemRegistrationScreen.tsx
>          <View style={styles.contentsWrapper}>
제가 작업한 환경에서 화면이 안잘려서 놓치고 있었는데 1번 문제는 확실히 ScrollView로 바꾸는게 나아보이네요 😢
2번 문제는 실수로 contentsWrapper View를 하나 더 넣어서 발생한 문제였습니다 ㅎㅎ.. 바로 수정할게요!

2024-08-30 09:00 UTC, crucial-sub commented on src/components/lostItem/CategorySelector.tsx
> +  const getCategoryText = () => {
이 부분은 선택완료 버튼 활성화 로직은 아니고 카테고리 선택 스크린으로 이동하는 버튼의 우측에 표시할 텍스트를 정하는 로직이에요!
이 때 "해당없음"의 경우 main만 있고 하위 sub 카테고리가 없어서 예외처리를 위해 main은 있는데 sub가 없는 경우를 조사할 필요가 있었어요
아래 순서와 같이 작동합니다 :)
1. 가장 먼저 main이 없을 경우, 선택한 카테고리가 없다는 뜻이므로 아무것도 표시하지 않기 위해 null return
2. main은 있는데 sub가 없을 경우 "해당없음"을 고른 경우이고, 이때는 main만 return
3. 위의 로직을 모두 통과한 경우, 선택한 카테고리가 있으며 "해당없음"이 아닌 경우이므로 main과 sub 모두 표시

이외에 구조분해할당 제안은 확실히 가독성이 더 좋아보이네요 바로 적용하겠습니다 ㅎㅎ

2024-08-30 09:03 UTC, crucial-sub commented on src/components/lostItem/CategorySelector.tsx
> +  const getCategoryText = () => {
말씀해주신대로 모든 상황에 대해 코드 의미를 좀더 명확하게 하기 위해
```typescript
const getCategoryText = () => {
    const {main, sub} = category;
    if (main && sub) return `${main}>${sub}`;
    else if (main && !sub) return main;
    return null;
  };
```
이런식으로 하는게 나을까요?

2024-08-30 09:14 UTC, crucial-sub commented on src/components/lostItem/ColorSelector.tsx
> +  const getColorText = () => {
넵 훨씬 간결하네요 :)

2024-08-30 09:16 UTC, comme-modee commented on src/components/lostItem/CategorySelector.tsx
> +  const getCategoryText = () => {
한가지 궁금한게 있어요. 서브카테고리를 선택하지 않으면 카테고리 등록이 되지 않던데 메인카테고리만 선택하는 경우가 있을 수 있나요?

2024-08-30 09:33 UTC, crucial-sub commented on src/components/lostItem/CategorySelector.tsx
> +  const getCategoryText = () => {
"해당없음"의 경우는 서브카테고리가 존재하지 않아서 메인카테고리밖에 선택이 안돼요!
그래서 카테고리 등록 로직에서도 "해당없음"을 고르면 서브카테고리 없이도 카테고리 등록이 가능하도록 구현해놨습니다 :)


```typescript

const isComplete =
    (selectedMain && selectedSub) || selectedMain === MainCategory.NONE;
```
위 코드에서 
1. main과 sub를 모두 선택한 경우
2. 선택한 main이 MainCategory.NONE(해당없음)인 경우

두 가지 경우에서 카테고리 등록이 가능해집니다!

2024-08-30 10:01 UTC, crucial-sub commented on src/components/lostItem/CategorySelector.tsx
> +  const getCategoryText = () => {
안드로이드 에뮬레이터 수정님 환경에 맞춰서 pixel 2로 구동해보니 "해당없음" 카테고리가 선택완료 버튼에 가려서 잘안보이네요 이제보니...ㅠㅠ

![Simulator Screenshot - iPhone 14 - 2024-08-30 at 18 58 12](https://github.com/user-attachments/assets/9ab55cd8-e6e0-4930-a706-cd45ba84f73a)

맨밑에 해당없음 카테고리 고르면 이런식으로 나타납니다 원래는 ㅠ

2024-08-30 10:14 UTC, crucial-sub commented on src/components/lostItem/CategorySelector.tsx
> +  const getCategoryText = () => {
전체적으로 UI 한번 손봐야겠네요.. 우선 이부분은 메인 카테고리 스크롤이 선택완료 버튼 위치보다 높게 스크롤이 가능하도록 하는 방향으로 수정해볼게요..!

2024-08-31 09:48 UTC, comme-modee commented on src/components/lostItem/CategorySelector.tsx
> +  const getCategoryText = () => {
아하..!! 해당없음이 아래에 가려져서 안보였던 거군요. 넵, 이해했습니다^^

2024-08-31 14:30 UTC, SeongHo5 commented on src/components/lostItem/ImagePicker.tsx
안녕하세요!
백엔드도 해당 화면 관련해서 기능 명세랑 화면이 달라서 문의 드렸었는데
이미지는 1장까지가 맞다고 하네요. 확인 부탁드립니다!
![image](https://github.com/user-attachments/assets/7a3b4742-1d94-47dd-9db3-fbdc22ac8e8e)

2024-09-06 08:02 UTC, crucial-sub commented
수정사항 반영해서 재작업하였고, 몇가지 안내 및 변경사항이 있습니다!

### **keyboard avoiding 기능**
안드로이드의 경우 manifest 파일에 windowSoftInputMode 속성값이 "adjustResize"로 되어있다면,
키보드가 올라올 때 자동으로 키보드를 제외한 나머지 화면의 높이를 100%로 다시 계산하여 앱에 적용시킵니다.
그래서 별다른 설정없이 ScrollView로 감싸주기만 해도 키보드 회피 기능이 쉽게 구현되죠 👍

하지만 iOS에서는 키보드가 올라오더라도 자동으로 전체 높이를 조절해주지 않기 때문에,
RN에서 제공해주는 기본 컴포넌트인 `KeyboardAvoidingView`를 통해 키보드 회피 기능을 구현하게 됩니다 보통👀
그런데 분실물 등록 스크린을 작업하면서 확인해보니 `KeyboardAvoidingView`가 멀티라인 속성이 있는 textInput에 대해서는 작동이 안하는 이슈가 있었습니다😱

그래서 처음 올린 PR에서 1차적으로 `KeyboardAwareScrollView` 라이브러리와 `reanimated` 애니메이션을 활용해서
키보드 회피 기능이 iOS의 multiline textInput에도 적용되면서 하단의 버튼도 매끄럽게 키보드 위로 올라오도록 구현해보았지만,
애니메이션 관련 로직이 다소 복잡하고, `KeyboardAwareScrollView` 라이브러리가 iOS를 위해 만들어진 느낌이라...
안드로이드에서는 오히려 기본 ScrollView로 구현했을 때가 더 매끄럽게 작동하는 느낌이었습니다😢

그래서 다른 방법을 찾아보았고, `AvoidSoftInput`이라는 라이브러리를 활용하여 안드로이드와 iOS에 모두 대응 가능한 커스텀 컴포넌트를 작성하였습니다.
iOS에서 multiline textInput이 사용될 때를 제외하면 기본 `KeyboardAvoidingView`와 `ScrollView`만으로도 키보드 회피 기능이 잘 작동하였기에 커스텀 컴포넌트에서도 기본적으로는 이를 그대로 사용합니다.
```typescript
const KeyboardAvoidingWrapper = () => {

  ...

  const dismissKeyboard = () => {
    Keyboard.dismiss();
  };

  return (
    // 빈 화면 터치 시 키보드가 바로 내려가도록 TouchableWithoutFeedback으로 감싸줌
    <TouchableWithoutFeedback onPress={dismissKeyboard}>
      <KeyboardAvoidingView
        behavior={isIOS ? 'padding' : undefined}>
        // ScrollView는 KeyboardAvoidingWrapper를 사용할 스크린에서 별도로 배치
        {children}
      </KeyboardAvoidingView>
    </TouchableWithoutFeedback>
  );
};
```
그리고 iOS이면서 multiline textInput을 사용할 때는 별도로 `AvoidSoftInput`을 통해 키보드 회피 기능이 구현됩니다.
```typescript
    if (isIOS && withMultiline) {
        // AvoidSoftInput 코드
    }
```


### **스크린 작업 시 요소들을 어떻게 배치할지?**
수정님이 요청주셨던대로 기존에 View로 감쌌던 부분들을 `ScrollView`로 바꿈과 동시에 Keyboard Avoiding 작업을 하면서 아래와 같이 요소들을 배치하였고, 추후 스크린 작업 진행시에도 이런식으로 하면 어떨까 합니다 :)
- 최상위 요소는 항상 `SafeAreaView` (style에 `flex:1` 설정 필수)
- 스크린에 textInput이 사용된다면 `KeyboardAvoidingWrapper`를 두번째로 배치(textInput 없으면 생략)
-> 이때 multiline textInput이라면 `withMultiline={true}`를 props로 전달(기본값은 false)
- 앞선 큰 틀의 배치가 끝나면 대부분의 경우 다음 3가지 파트로 나눔
   - 상단 GNB헤더
   - 콘텐츠
   -> 앞서 `KeyboardAvoidingWrapper`를 배치했다면 반드시 여기서 `ScrollView`로 감싸줘야하고, 
   그렇지 않았더라도 예기치 못하게 내부 요소가 잘리는 상황을 방지하기위해 `ScrollView`로 감싸주는것을 권장)
   이때 contentContainerStyle에 `flexGrow: 1` 및 `showsVerticalScrollIndicator={false}` 설정 권장
   - 하단 버튼(없다면 생략)
   -> 스크린 하단과 버튼 사이에 여백을 주기위해 우선 View로 감싸고 padding값이나 bottom값으로 위치 조정을 해두었습니다!
   
아래는 프로필 설정 스크린에서 작업한 예시입니다 :)
```typescript
<SafeAreaView style={styles.container}>
   <KeyboardAvoidingWrapper>
      <BackBtnGnbHeader title="프로필 설정" />
      <ScrollView
          contentContainerStyle={styles.scrollContent}
          showsVerticalScrollIndicator={false}>
          ...
      </ScrollView>
      <View style={styles.btnBox}>
          <PrimaryLargeBtn ... />
      </View>
   </KeyboardAvoidingWrapper>
</SafeAreaView>
```


### 분실물 이미지 등록 기능 변경
성호님이 확인해주셨던대로 이미지 등록할 때 한장만 등록하도록 수정해두었고,
이에 따라 useImagePicker 커스텀훅도 사진 한장만 고르는 로직으로 바꿔놓았습니다 :)

2024-09-09 07:34 UTC, comme-modee requested changes
수고하셨습니다! screens에 FoundItem, Home, LostItem 폴더명을 카멜케이스로 변경 후 머지부탁드립니다 :)

2024-09-09 15:01 UTC, merged